[project]
name = "esphome-config"
version = "0.0.0"

[tool.semantic_release]
tag_format = "{version}"
version_toml = ["pyproject.toml:project.version"]
major_on_zero = false
allow_zero_version = true

[tool.semantic_release.commit_parser_options]
allowed_tags = [
  "build", "chore", "ci", "deps", "docs", "hotfix", "feat", "fix", "perf",
  "style", "refactor", "test",
]
minor_tags = ["feat"]
patch_tags = ["deps", "fix", "hotfix", "perf", "build"]
parse_squash_commits = false
